# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  print-hello:
    docker:
     - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say Hello world again"
          command: "echo Hello, World again!"
  print-world:
    docker:
     - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say world"
          command: "echo World!"
workflows:
  welcome:
    jobs:
      - print-hello
      - print_world:
        requires:
           - say-hello

